sudo: false
language: node_js
cache:
  directories:
    - ~/.npm
node_js:
  - "8.3"
notifications:
  email: false
after_success:
  - npm run travis-deploy-once "npm run semantic-release"
  - npm run coveralls
branches:
  except:
    - /^v\d+\.\d+\.\d+$/